{% set name = "scikit-explain" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5dd646d049c26be707f1222482596184886d57fcd876c590884941e97089b10b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools

  run:
    - ipywidgets
    - lime >=0.2.0
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn >=1.0.0
    - seaborn >=0.11.0
    - shap >=0.30.0
    - statsmodels
    - tqdm
    - xarray >=0.16.0

test:
  requires:
    - pip
  commands:
    - pip check

  imports:
    - skexplain
    - skexplain.common
    - skexplain.main
    - skexplain.main.PermutationImportance
    - skexplain.plot

about:
  home: https://github.com/monte-flora/scikit-explain/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A user-friendly python package for computing and plotting machine learning explainability output.
  doc_url: https://scikit-explain.readthedocs.io
  dev_url: https://github.com/monte-flora/scikit-explain/

extra:
  recipe-maintainers:
    - monte-flora
